"""Agent-mode case data initialization module.

Called inside the container before the interactive shell opens.
Fetches case metadata from Red Hat API and writes structured files
to the case workspace directory.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
from datetime import date

logger = logging.getLogger(__name__)

CASE_DIR = "/case"  # container mount point; overridable in tests via parameter


def init_case_data(case_number: str, case_dir: str = CASE_DIR) -> None:
    """Fetch case data from Red Hat API and write files to case directory.

    Called inside the container before the interactive shell opens.
    On any SFDC API failure: prints warning and returns (does not raise).
    On OCM failure: prints warning, skips ocm-cluster.json, continues.
    All files are always overwritten (no skip-if-exists logic).

    Args:
        case_number: 8-digit case number
        case_dir: Directory to write files to (default: /case)
    """
    # 1. Load offline token from config
    from mc.config.manager import ConfigManager

    config_mgr = ConfigManager()
    config = config_mgr.load()
    offline_token = config.get("api", {}).get("rh_api_offline_token") or config.get("api", {}).get("offline_token")
    if not offline_token:
        print("Warning: No offline token in config — cannot fetch case data")
        return

    # 2. Exchange for access token
    from mc.utils.auth import get_access_token

    try:
        access_token = get_access_token(offline_token)
    except Exception as e:
        print(f"Warning: Failed to authenticate for case data fetch: {e}")
        return

    # 3. Fetch case details (non-fatal on failure)
    from mc.integrations.redhat_api import RedHatAPIClient

    try:
        api_client = RedHatAPIClient(access_token)
        case_details = api_client.fetch_case_details(case_number)
    except Exception as e:
        print(f"Warning: Failed to fetch case details: {e}")
        return

    # 4. Fetch comments (non-fatal on failure — write empty list on failure)
    try:
        comments = api_client.fetch_case_comments(case_number)
    except Exception as e:
        print(f"Warning: Failed to fetch case comments: {e}")
        comments = []

    # 5. Write sfdc-case.json to sfdc/ subdirectory
    sfdc_dir = os.path.join(case_dir, "sfdc")
    os.makedirs(sfdc_dir, exist_ok=True)
    sfdc_case_path = os.path.join(sfdc_dir, "sfdc-case.json")
    with open(sfdc_case_path, "w") as f:
        json.dump(case_details, f, indent=2)

    # 6. Write sfdc-comments.json to sfdc/ subdirectory
    sfdc_comments_path = os.path.join(sfdc_dir, "sfdc-comments.json")
    with open(sfdc_comments_path, "w") as f:
        json.dump(comments, f, indent=2)

    # 7. Extract fields for case.env
    cluster_external_id = str(case_details.get("openshiftClusterID") or "")
    customer_name = str(case_details.get("customerName") or case_details.get("accountNumberRef") or "")
    summary = str(case_details.get("summary") or "")
    severity = str(case_details.get("severity") or "")
    status = str(case_details.get("status") or "")
    product = str(case_details.get("product") or "")

    # 8. Write case.env — MC_ prefixed, double-quoted values, header comment
    env_path = os.path.join(case_dir, "case.env")
    lines = [
        f"# Generated by mc on {date.today().isoformat()} for case {case_number}",
        f'MC_CASE_NUMBER="{case_number}"',
        f'MC_CUSTOMER_NAME="{customer_name}"',
        f'MC_SUMMARY="{summary}"',
        f'MC_SEVERITY="{severity}"',
        f'MC_STATUS="{status}"',
        f'MC_PRODUCT="{product}"',
        f'MC_CLUSTER_EXTERNAL_ID="{cluster_external_id}"',
    ]
    with open(env_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    # 9. If cluster_external_id is non-empty, run ocm get cluster (non-fatal)
    if cluster_external_id:
        try:
            result = subprocess.run(
                ["ocm", "get", "cluster", cluster_external_id],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                ocm_cluster_path = os.path.join(case_dir, "ocm-cluster.json")
                with open(ocm_cluster_path, "w") as f:
                    f.write(result.stdout)
            else:
                print(f"Warning: ocm get cluster failed (exit {result.returncode}): {result.stderr.strip()}")
        except subprocess.TimeoutExpired:
            print("Warning: ocm get cluster timed out — skipping ocm-cluster.json")
        except FileNotFoundError:
            print("Warning: ocm binary not found — skipping ocm-cluster.json")
        except Exception as e:
            print(f"Warning: ocm get cluster failed: {e}")
