"""Unit tests for mc.agent.case_data module."""
from __future__ import annotations

import json
import os
import re

import pytest

from mc.agent.case_data import init_case_data


# ---------------------------------------------------------------------------
# Shared helpers / fixtures
# ---------------------------------------------------------------------------

CASE_NUMBER = "12345678"

BASE_CASE_DETAILS: dict = {
    "summary": "Pod OOMKilled on prod",
    "accountNumberRef": "9876543",
    "status": "Open",
    "severity": "2 (High)",
    "product": "OpenShift Container Platform",
    "customerName": "Acme Corp",
}

BASE_CASE_DETAILS_WITH_CLUSTER: dict = {
    **BASE_CASE_DETAILS,
    "openshiftClusterID": "abc-cluster-123",
}


def _mock_init(mocker, case_details: dict, *, comments_raises: bool = False) -> None:
    """Wire up common mocks for init_case_data.

    Since ConfigManager, get_access_token, and RedHatAPIClient are imported
    inside init_case_data() we patch at their original module paths.
    """
    mock_config_mgr = mocker.MagicMock()
    mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
    mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)

    mocker.patch("mc.utils.auth.get_access_token", return_value="access_token")

    mock_api = mocker.MagicMock()
    mock_api.fetch_case_details.return_value = case_details
    if comments_raises:
        mock_api.fetch_case_comments.side_effect = Exception("comments API down")
    else:
        mock_api.fetch_case_comments.return_value = [{"id": "c1", "text": "First comment"}]

    mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api)


# ---------------------------------------------------------------------------
# case.env format tests
# ---------------------------------------------------------------------------

class TestCaseEnvFormat:
    def test_case_env_mc_cluster_external_id_present_when_empty(self, tmp_path, mocker):
        """MC_CLUSTER_EXTERNAL_ID line is written even when API returns no cluster ID."""
        _mock_init(mocker, BASE_CASE_DETAILS)  # no openshiftClusterID key
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        assert 'MC_CLUSTER_EXTERNAL_ID=""' in env_content

    def test_case_env_mc_cluster_external_id_present_when_set(self, tmp_path, mocker):
        """MC_CLUSTER_EXTERNAL_ID contains the cluster ID from API."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(returncode=1, stderr="not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        assert 'MC_CLUSTER_EXTERNAL_ID="abc-cluster-123"' in env_content

    def test_case_env_all_values_double_quoted(self, tmp_path, mocker):
        """Every non-comment line in case.env uses KEY="value" format."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        for line in env_content.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            assert re.match(r'^[A-Z_]+=".+"$', line) or re.match(r'^[A-Z_]+=""$', line), (
                f"Line not in KEY=\"value\" format: {line!r}"
            )

    def test_case_env_has_header_comment(self, tmp_path, mocker):
        """First line of case.env starts with '# Generated by mc'."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        first_line = (tmp_path / "case.env").read_text().splitlines()[0]
        assert first_line.startswith("# Generated by mc")

    def test_case_env_has_mc_prefix_on_all_vars(self, tmp_path, mocker):
        """Every variable line in case.env starts with 'MC_'."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        for line in env_content.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            assert line.startswith("MC_"), f"Variable without MC_ prefix: {line!r}"


# ---------------------------------------------------------------------------
# File writing tests
# ---------------------------------------------------------------------------

class TestFileWriting:
    def test_sfdc_case_json_written(self, tmp_path, mocker):
        """sfdc-case.json is created in case_dir."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "sfdc-case.json").exists()

    def test_sfdc_case_json_is_valid_json(self, tmp_path, mocker):
        """sfdc-case.json contains valid JSON matching the mock response."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        data = json.loads((tmp_path / "sfdc-case.json").read_text())
        assert data["summary"] == BASE_CASE_DETAILS["summary"]
        assert data["status"] == BASE_CASE_DETAILS["status"]

    def test_sfdc_comments_json_written(self, tmp_path, mocker):
        """sfdc-comments.json is created in case_dir."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "sfdc-comments.json").exists()

    def test_case_env_written(self, tmp_path, mocker):
        """case.env is created in case_dir."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "case.env").exists()

    def test_files_overwritten_on_each_call(self, tmp_path, mocker):
        """Files are overwritten on subsequent calls (no skip-if-exists logic)."""
        # First call
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))
        first_content = (tmp_path / "sfdc-case.json").read_text()

        # Second call with different case details
        updated_details = {**BASE_CASE_DETAILS, "summary": "Updated summary after second call"}
        mock_config_mgr2 = mocker.MagicMock()
        mock_config_mgr2.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr2)
        mocker.patch("mc.utils.auth.get_access_token", return_value="access_token2")
        mock_api2 = mocker.MagicMock()
        mock_api2.fetch_case_details.return_value = updated_details
        mock_api2.fetch_case_comments.return_value = []
        mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api2)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        second_content = (tmp_path / "sfdc-case.json").read_text()
        assert first_content != second_content
        assert "Updated summary after second call" in second_content


# ---------------------------------------------------------------------------
# OCM conditional behavior
# ---------------------------------------------------------------------------

class TestOcmBehavior:
    def test_ocm_cluster_json_written_when_cluster_id_present(self, tmp_path, mocker):
        """ocm-cluster.json is written when cluster ID is present and ocm succeeds."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(
                returncode=0,
                stdout='{"kind": "Cluster", "id": "abc-cluster-123"}',
            ),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        ocm_path = tmp_path / "ocm-cluster.json"
        assert ocm_path.exists()
        assert "abc-cluster-123" in ocm_path.read_text()

    def test_ocm_cluster_json_not_written_when_cluster_id_absent(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when API returns no cluster ID."""
        _mock_init(mocker, BASE_CASE_DETAILS)  # no openshiftClusterID
        mock_subprocess = mocker.patch("subprocess.run")

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()
        mock_subprocess.assert_not_called()

    def test_ocm_cluster_json_not_written_when_ocm_fails(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when ocm exits non-zero; execution continues."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(returncode=1, stderr="Error: cluster not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()
        # Other files should still have been written
        assert (tmp_path / "sfdc-case.json").exists()
        assert (tmp_path / "case.env").exists()

    def test_ocm_cluster_json_not_written_when_ocm_timeout(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written on timeout; warning printed, no raise."""
        import subprocess as sp_module

        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            side_effect=sp_module.TimeoutExpired(cmd="ocm", timeout=30),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()

    def test_ocm_cluster_json_not_written_when_ocm_binary_missing(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when ocm binary is not found."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            side_effect=FileNotFoundError("ocm not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()


# ---------------------------------------------------------------------------
# Failure handling
# ---------------------------------------------------------------------------

class TestFailureHandling:
    def test_sfdc_api_failure_prints_warning_does_not_raise(self, tmp_path, mocker, capsys):
        """When authentication fails, warning is printed and function returns silently."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)
        mocker.patch(
            "mc.utils.auth.get_access_token",
            side_effect=Exception("invalid token"),
        )

        # Must not raise
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert "Warning" in captured.out

    def test_case_details_failure_prints_warning_does_not_raise(self, tmp_path, mocker, capsys):
        """When fetch_case_details fails, warning is printed and function returns silently."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)
        mocker.patch("mc.utils.auth.get_access_token", return_value="access_token")
        mock_api = mocker.MagicMock()
        mock_api.fetch_case_details.side_effect = Exception("API down")
        mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert "Warning" in captured.out
        # No files should be written
        assert not (tmp_path / "sfdc-case.json").exists()

    def test_comments_api_failure_writes_empty_list(self, tmp_path, mocker):
        """When fetch_case_comments fails, sfdc-comments.json is written as empty array."""
        _mock_init(mocker, BASE_CASE_DETAILS, comments_raises=True)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        comments_path = tmp_path / "sfdc-comments.json"
        assert comments_path.exists()
        assert json.loads(comments_path.read_text()) == []

    def test_no_offline_token_prints_warning_does_not_raise(self, tmp_path, mocker, capsys):
        """When no offline token is configured, warning is printed and function returns."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert "Warning" in captured.out
        assert not (tmp_path / "sfdc-case.json").exists()
