"""Unit tests for mc.agent.case_data module."""
from __future__ import annotations

import json
import os
import re

import pytest

from mc.agent.case_data import init_case_data


# ---------------------------------------------------------------------------
# Shared helpers / fixtures
# ---------------------------------------------------------------------------

CASE_NUMBER = "12345678"

BASE_CASE_DETAILS: dict = {
    "summary": "Pod OOMKilled on prod",
    "accountNumberRef": "9876543",
    "status": "Open",
    "severity": "2 (High)",
    "product": "OpenShift Container Platform",
    "customerName": "Acme Corp",
}

BASE_CASE_DETAILS_WITH_CLUSTER: dict = {
    **BASE_CASE_DETAILS,
    "openshiftClusterID": "abc-cluster-123",
}


def _mock_init(mocker, case_details: dict, *, comments_raises: bool = False) -> None:
    """Wire up common mocks for init_case_data.

    Since ConfigManager, get_access_token, and RedHatAPIClient are imported
    inside init_case_data() we patch at their original module paths.
    """
    mock_config_mgr = mocker.MagicMock()
    mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
    mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)

    mocker.patch("mc.utils.auth.get_access_token", return_value="access_token")

    mock_api = mocker.MagicMock()
    mock_api.fetch_case_details.return_value = case_details
    if comments_raises:
        mock_api.fetch_case_comments.side_effect = Exception("comments API down")
    else:
        mock_api.fetch_case_comments.return_value = [{"id": "c1", "text": "First comment"}]

    mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api)


# ---------------------------------------------------------------------------
# case.env format tests
# ---------------------------------------------------------------------------

class TestCaseEnvFormat:
    def test_case_env_mc_cluster_external_id_present_when_empty(self, tmp_path, mocker):
        """MC_CLUSTER_EXTERNAL_ID line is written even when API returns no cluster ID."""
        _mock_init(mocker, BASE_CASE_DETAILS)  # no openshiftClusterID key
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        assert 'MC_CLUSTER_EXTERNAL_ID=""' in env_content

    def test_case_env_mc_cluster_external_id_present_when_set(self, tmp_path, mocker):
        """MC_CLUSTER_EXTERNAL_ID contains the cluster ID from API."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(returncode=1, stderr="not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        assert 'MC_CLUSTER_EXTERNAL_ID="abc-cluster-123"' in env_content

    def test_case_env_all_values_double_quoted(self, tmp_path, mocker):
        """Every non-comment line in case.env uses KEY="value" format."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        for line in env_content.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            assert re.match(r'^[A-Z_]+=".+"$', line) or re.match(r'^[A-Z_]+=""$', line), (
                f"Line not in KEY=\"value\" format: {line!r}"
            )

    def test_case_env_has_header_comment(self, tmp_path, mocker):
        """First line of case.env starts with '# Generated by mc'."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        first_line = (tmp_path / "case.env").read_text().splitlines()[0]
        assert first_line.startswith("# Generated by mc")

    def test_case_env_has_mc_prefix_on_all_vars(self, tmp_path, mocker):
        """Every variable line in case.env starts with 'MC_'."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        env_content = (tmp_path / "case.env").read_text()
        for line in env_content.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            assert line.startswith("MC_"), f"Variable without MC_ prefix: {line!r}"


# ---------------------------------------------------------------------------
# File writing tests
# ---------------------------------------------------------------------------

class TestFileWriting:
    def test_sfdc_case_json_written(self, tmp_path, mocker):
        """sfdc-case.json is created in case_dir/sfdc/."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "sfdc" / "sfdc-case.json").exists()

    def test_sfdc_case_json_is_valid_json(self, tmp_path, mocker):
        """sfdc-case.json contains valid JSON matching the mock response."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        data = json.loads((tmp_path / "sfdc" / "sfdc-case.json").read_text())
        assert data["summary"] == BASE_CASE_DETAILS["summary"]
        assert data["status"] == BASE_CASE_DETAILS["status"]

    def test_sfdc_comments_json_written(self, tmp_path, mocker):
        """sfdc-comments.json is created in case_dir/sfdc/."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "sfdc" / "sfdc-comments.json").exists()

    def test_case_env_written(self, tmp_path, mocker):
        """case.env is created in case_dir."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (tmp_path / "case.env").exists()

    def test_files_overwritten_on_each_call(self, tmp_path, mocker):
        """Files are overwritten on subsequent calls (no skip-if-exists logic)."""
        # First call
        _mock_init(mocker, BASE_CASE_DETAILS)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))
        first_content = (tmp_path / "sfdc" / "sfdc-case.json").read_text()

        # Second call with different case details
        updated_details = {**BASE_CASE_DETAILS, "summary": "Updated summary after second call"}
        mock_config_mgr2 = mocker.MagicMock()
        mock_config_mgr2.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr2)
        mocker.patch("mc.utils.auth.get_access_token", return_value="access_token2")
        mock_api2 = mocker.MagicMock()
        mock_api2.fetch_case_details.return_value = updated_details
        mock_api2.fetch_case_comments.return_value = []
        mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api2)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        second_content = (tmp_path / "sfdc" / "sfdc-case.json").read_text()
        assert first_content != second_content
        assert "Updated summary after second call" in second_content


# ---------------------------------------------------------------------------
# OCM conditional behavior
# ---------------------------------------------------------------------------

class TestOcmBehavior:
    def test_ocm_cluster_json_written_when_cluster_id_present(self, tmp_path, mocker):
        """ocm-cluster.json is written when cluster ID is present and ocm succeeds."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(
                returncode=0,
                stdout=json.dumps({"kind": "ClusterList", "total": 1, "items": [{"kind": "Cluster", "id": "abc-cluster-123"}]}),
            ),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        ocm_path = tmp_path / "ocm-cluster.json"
        assert ocm_path.exists()
        data = json.loads(ocm_path.read_text())
        assert data["id"] == "abc-cluster-123"
        assert data["kind"] == "Cluster"

    def test_ocm_cluster_json_not_written_when_cluster_id_absent(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when API returns no cluster ID."""
        _mock_init(mocker, BASE_CASE_DETAILS)  # no openshiftClusterID
        mock_subprocess = mocker.patch("subprocess.run")

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()
        mock_subprocess.assert_not_called()

    def test_ocm_cluster_json_not_written_when_ocm_fails(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when ocm exits non-zero; execution continues."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(returncode=1, stderr="Error: cluster not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()
        # Other files should still have been written
        assert (tmp_path / "sfdc" / "sfdc-case.json").exists()
        assert (tmp_path / "case.env").exists()

    def test_ocm_cluster_json_not_written_when_ocm_timeout(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written on timeout; warning printed, no raise."""
        import subprocess as sp_module

        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            side_effect=sp_module.TimeoutExpired(cmd="ocm", timeout=30),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()

    def test_ocm_cluster_json_not_written_when_ocm_binary_missing(self, tmp_path, mocker):
        """ocm-cluster.json is NOT written when ocm binary is not found."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mocker.patch(
            "subprocess.run",
            side_effect=FileNotFoundError("ocm not found"),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert not (tmp_path / "ocm-cluster.json").exists()

    def test_ocm_lookup_uses_search_api_with_external_id(self, tmp_path, mocker):
        """OCM lookup must use search API with external_id, not naive 'ocm get cluster <id>'."""
        _mock_init(mocker, BASE_CASE_DETAILS_WITH_CLUSTER)
        mock_run = mocker.patch(
            "subprocess.run",
            return_value=mocker.MagicMock(
                returncode=0,
                stdout=json.dumps({
                    "kind": "ClusterList",
                    "total": 1,
                    "items": [{"kind": "Cluster", "id": "abc-cluster-123", "external_id": "abc-cluster-123"}],
                }),
            ),
        )
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        mock_run.assert_called_once()
        cmd = mock_run.call_args[0][0]
        # Must use the search API endpoint, not the naive form
        assert "/api/clusters_mgmt/v1/clusters" in cmd, (
            f"Expected search API endpoint in command, got: {cmd}"
        )
        # Must include external_id in search parameter
        cmd_str = " ".join(cmd)
        assert "external_id" in cmd_str, (
            f"Expected 'external_id' in search parameter, got: {cmd_str}"
        )
        # Must NOT be the naive ['ocm', 'get', 'cluster', <id>] form
        assert cmd != ["ocm", "get", "cluster", "abc-cluster-123"], (
            "Must not use naive 'ocm get cluster <id>' — OCM expects internal ID, not external_id"
        )


# ---------------------------------------------------------------------------
# Failure handling
# ---------------------------------------------------------------------------

class TestFailureHandling:
    def test_sfdc_api_failure_silent_does_not_raise(self, tmp_path, mocker, capsys):
        """When authentication fails, function returns silently with no stdout output."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)
        mocker.patch(
            "mc.utils.auth.get_access_token",
            side_effect=Exception("invalid token"),
        )

        # Must not raise
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert captured.out == "", (
            "init_case_data() must produce no stdout on auth failure (use logger.debug not print)"
        )

    def test_case_details_failure_silent_does_not_raise(self, tmp_path, mocker, capsys):
        """When fetch_case_details fails, function returns silently with no stdout output."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {"rh_api_offline_token": "tok"}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)
        mocker.patch("mc.utils.auth.get_access_token", return_value="access_token")
        mock_api = mocker.MagicMock()
        mock_api.fetch_case_details.side_effect = Exception("API down")
        mocker.patch("mc.integrations.redhat_api.RedHatAPIClient", return_value=mock_api)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert captured.out == "", (
            "init_case_data() must produce no stdout on case details failure (use logger.debug not print)"
        )
        # No files should be written
        assert not (tmp_path / "sfdc" / "sfdc-case.json").exists()

    def test_comments_api_failure_writes_empty_list(self, tmp_path, mocker):
        """When fetch_case_comments fails, sfdc-comments.json is written as empty array."""
        _mock_init(mocker, BASE_CASE_DETAILS, comments_raises=True)
        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        comments_path = tmp_path / "sfdc" / "sfdc-comments.json"
        assert comments_path.exists()
        assert json.loads(comments_path.read_text()) == []

    def test_no_offline_token_silent_does_not_raise(self, tmp_path, mocker, capsys):
        """When no offline token is configured, function returns silently with no stdout output."""
        mock_config_mgr = mocker.MagicMock()
        mock_config_mgr.load.return_value = {"api": {}}
        mocker.patch("mc.config.manager.ConfigManager", return_value=mock_config_mgr)

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        captured = capsys.readouterr()
        assert captured.out == "", (
            "init_case_data() must produce no stdout when token is absent (use logger.debug not print)"
        )
        assert not (tmp_path / "sfdc" / "sfdc-case.json").exists()


# ---------------------------------------------------------------------------
# SFDC file path regression tests (fix/sfdc-file-save-path, MC-73)
# ---------------------------------------------------------------------------


@pytest.mark.backwards_compatibility
class TestSfdcFilePathRegression:
    """Verify sfdc-case.json and sfdc-comments.json are written to the sfdc/ subdirectory."""

    def test_sfdc_case_json_written_to_sfdc_subdirectory(self, tmp_path, mocker):
        """sfdc-case.json must be written to <case_dir>/sfdc/sfdc-case.json, not case root."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        sfdc_dir = tmp_path / "sfdc"
        sfdc_dir.mkdir()

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (sfdc_dir / "sfdc-case.json").exists(), (
            f"sfdc-case.json not at {sfdc_dir}/sfdc-case.json — written to case root instead"
        )

    def test_sfdc_comments_json_written_to_sfdc_subdirectory(self, tmp_path, mocker):
        """sfdc-comments.json must be written to <case_dir>/sfdc/sfdc-comments.json."""
        _mock_init(mocker, BASE_CASE_DETAILS)
        sfdc_dir = tmp_path / "sfdc"
        sfdc_dir.mkdir()

        init_case_data(CASE_NUMBER, case_dir=str(tmp_path))

        assert (sfdc_dir / "sfdc-comments.json").exists(), (
            f"sfdc-comments.json not at {sfdc_dir}/sfdc-comments.json — written to case root"
        )
